version: 1
services:
  - type: web
    name: enoch-shopping
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn enoch_shopping.wsgi:application
    plan: free
clear