# Generated by Django 5.1.1 on 2024-10-24 08:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltypointhistory',
            name='reason',
            field=models.CharField(choices=[('reward', 'Reward'), ('promotion', 'Promotion'), ('referral', 'Referral'), ('purchase', 'Purchase'), ('other', 'Other')], default=datetime.datetime(2024, 10, 24, 8, 44, 5, 336805, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='Reason for Change'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged Item'), ('wrong_item', 'Wrong Item Sent'), ('not_satisfied', 'Not Satisfied with the Item'), ('other', 'Other')], max_length=50)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
