# Generated by Django 5.0 on 2026-10-08 00:00
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("country_codes", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("carrier", models.CharField(blank=True, default="Local Courier", max_length=120)),
                ("tracking_number", models.CharField(blank=True, max_length=120, unique=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("picked_up", "Picked up"), ("in_transit", "In transit"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("returned", "Returned")], default="pending", max_length=30)),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("origin_address", models.CharField(blank=True, max_length=500)),
                ("origin_latitude", models.FloatField(blank=True, null=True)),
                ("origin_longitude", models.FloatField(blank=True, null=True)),
                ("destination_address", models.CharField(blank=True, max_length=500)),
                ("destination_latitude", models.FloatField(blank=True, null=True)),
                ("destination_longitude", models.FloatField(blank=True, null=True)),
                ("current_latitude", models.FloatField(blank=True, null=True)),
                ("current_longitude", models.FloatField(blank=True, null=True)),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="shipment", to="orders.order")),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("picked_up", "Picked up"), ("in_transit", "In transit"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("returned", "Returned")], default="in_transit", max_length=30)),
                ("status_note", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("shipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="locations", to="shipping.shipment")),
            ],
            options={"ordering": ["-timestamp"]},
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("created", "Order Created"), ("picked_up", "Picked Up"), ("departure", "Departed"), ("arrival", "Arrived"), ("out_for_delivery", "Out for Delivery"), ("attempted_delivery", "Delivery Attempted"), ("delivered", "Delivered"), ("exception", "Exception"), ("returned", "Returned"), ("lost", "Lost")], max_length=30)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("shipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="shipping.shipment")),
            ],
            options={"ordering": ["-timestamp"]},
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField()),
                ("status", models.CharField(choices=[("requested", "Requested"), ("approved", "Approved"), ("rejected", "Rejected"), ("received", "Received"), ("refunded", "Refunded")], default="requested", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="returns", to="orders.order")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.user")),
            ],
        ),
    ]
